exp_name: convnext_tiny

data:
  data_dir: data/ris2026-krog1-ucni
  test_dir: data/ris2026-krog1-testni
  csv_path: data/ucni_set.csv
  test_size: 0.2
  batch_size: 16
  num_workers: 4
  transform:
    height: 224
    width: 224
  augment:
    hf_prob: 0.5
    vf_prob: 0.5

model:
  arch: convnext_tiny
  dropout: 0.3

train:
  n_splits: 10
  weight_decay: 0.0001
  patience: 20
  label_smoothing: 0.1
  mixup: true
  phase1_lr: 0.001
  phase1_epochs: 20
  phase2_lr: 0.0001
  phase2_epochs: 60
  checkpoint_path: checkpoints/best_convnext.pth

test:
  n_tta: 8